import re
@udf(returnType=StringType())
def find_cat_i1(x):
    if re.match(r".*((not|cannot|unable|drop)[a-z\s]{0,20}(call)|(call)[a-z\s]{0,20}(not|cannot|unable|drop)).*", x):
        return("troubleshooting_call trouble")
    if re.match(r".*((((cannot|not)[a-z\s]{0,20}(send|receiv|get|deliver|forward|resend|work))|(problem|issue|fail))[a-z\s]{0,20}(text|msg|message| sms |imessage|video)|(text|msg|message| sms |imessage|video){0,20}(((cannot|not)[a-z\s]{0,20}(send|receiv|get|deliver|forward|resend|work))|(problem|issue|fail))).*", x):
        return("troubleshooting_trouble messaging")
    if re.match(r".*((crash|issue|problem|trouble no |slow|not work|troubleshoot|not working|not able|cannot use |horribl|terribl|disappoint|frustat| bad |poor|data intermittent)[a-z\s]{0,20}(internet|connect|mobile data| no bar| no data| no network|data)|(internet|connect|mobile data| no bar| no data| no network|data)[a-z\s]{0,20}(crash|issue|problem|trouble no |slow|not work|troubleshoot|not working|not able|cannot use |horribl|terribl|disappoint|frustat| bad |poor|data intermittent)|(no internet| no data)).*", x):
        return("troubleshooting_Data/internet trouble")
    if re.match(r".*((reconnect|agent assist|late|bill reprint|early termination|activation|upgrade|long distance|overage|reprint|damage device|damaged device|access|apple music|bill rerate|bogo|buyout|return|disney plus|downloads|download|equipment|inconvenience|insurance|international|late|number change|over draft|paperless billing|payment return|restock|shipment|trade in |data)[a-z\s]{0,20}(fee|charg)|(fee|charg)[a-z\s]{0,20}(reconnect|agent assist|late|bill reprint|early termination|activation|upgrade|long distance|overage|reprint|damage device|damaged device|access|apple music|bill rerate|bogo|buyout|return|disney plus|downloads|download|equipment|inconvenience|insurance|international|late|number change|over draft|paperless billing|payment return|restock|shipment|trade in |data)|(charg|pay|Know|how|why)[a-z\s]{0,20}(reconnect|agent assist|late|bill reprint|early termination|activation|upgrade|long distance|overage|reprint|damage device|damaged device|access|apple music|bill rerate|bogo|buyout|return|disney plus|downloads|download|equipment|inconvenience|insurance|international|late|number change|over draft|paperless billing|payment return|restock|shipment|trade in |data)|data boost).*", x):
        return("billing_specific charge inquiry")
    if re.match(r".*((refund|waiv|taken off|return|revers|issue|adjust|credit)[a-z\s]{0,20}(fee|charg|reconnect|agent assist|late|bill reprint|early termination|activation|upgrade|long distance|overage|reprint|damage device|damaged device|access|apple music|bill rerate|bogo|buyout|return|disney plus|downloads|download|equipment|inconvenience|insurance|international|late|number change|over draft|paperless billing|payment return|restock|shipment|trade in |data)|(fee|charg)[a-z\s]{0,20}waiv|(apply|issue)[a-z\s]{0,20}(adjust)|(fee|charg|reconnect|agent assist|late|bill reprint|early termination|activation|upgrade|long distance|overage|reprint|damage device|damaged device|access|apple music|bill rerate|bogo|buyout|return|disney plus|downloads|download|equipment|inconvenience|insurance|international|late|number change|over draft|paperless billing|payment return|restock|shipment|trade in |data)[a-z\s]{0,20}(refund|waiv|taken off|return|revers|issue|adjust|credit)|(appl|told|deny|denied|give|issue|receiv|get|know about|courtesy|incentive|applied|get|refund|return|reverse|charg|bill|have|move|offset)[a-z\s]{0,20}credit|credit[a-z\s]{0,20}(appl|told|deny|denied|give|issue|receiv|get|know about|courtesy|incentive|applied|get|refund|return|reverse|charg|bill|have|move|offset)).*", x):
        return("billing_credit request/get waiver")
    if re.match(r".*(access[a-z\s]{0,20}voicemail|voicemail[a-z\s]{0,20}access).*", x):
        return("international_query-voice mail")
    if re.match(r".*((phone|device|number)[a-z\s]{0,20}(lg |lumia|convoy|samsung|galaxy|cosmos|spectrum|ipad| mini |iphone|hotspot| mifi |windows phone|blackberry|casio|adamant|escapade|jetpack|nokia|motorola|modem| htc |thunderbolt|moto|pantech|lucid|motorola|router|voyager|ericsson|xperia|kyocera|razzle|one max|ellipsis|google pixel)|(lg |lumia|convoy|samsung|galaxy|cosmos|spectrum|ipad| mini |iphone|hotspot| mifi |windows phone|blackberry|casio|adamant|escapade|jetpack|nokia|motorola|modem| htc |thunderbolt|moto|pantech|lucid|motorola|router|voyager|ericsson|xperia|kyocera|razzle|one max|ellipsis|google pixel)[a-z\s]{0,20}(phone|device|number)).*", x):
        return("equipment_setup/activate phone")  
    if re.match(r".*((understand| go over|question|inquir|enquir|assistance|explain|read|view|see|fetch)[a-z\s]{0,20}bill|bill[a-z\s]{0,20}(understand| go over|question|inquir|enquir|assistance|explain|read|view|see|fetch)).*", x):
            return("billing_bill explanation")
    if re.match(r".*((assist|troubl|issue|problem|fail|error|fallout|try|help)[a-z\s]{0,20}activat|activat[a-z\s]{0,20}(assist|troubl|issue|problem|fail|error|fallout|try|help)).*", x):
            return("equipment_activation issue")
    if re.match(r".*((error|fail|issue|problem|fail|troubl|incorrect|wrong|should not|mistake)[a-z\s]{0,20}bill|bill[a-z\s]{0,20}(error|fail|issue|problem|fail|troubl|incorrect|wrong|should not|mistake)|(incorrect|wrong|should not)[a-z\s]{0,20}charg|charg[a-z\s]{0,20}(incorrect|wrong|should not)|(error|fail|issue|problem|fail|troubl|incorrect|wrong|should not|mistake)[a-z\s]{0,20}bill).*", x):
            return("Bill Error/Issues")	
    if re.match(r".*((issue|not work|error)[a-z\s]{0,20}(sim card|simcard|esimcard| esim )|(sim card|simcard|esimcard| esim )[a-z\s]{0,20}(issue|not work|error)).*", x):
            return("troubleshooting_Sim card Trouble")
    if re.match(r".*(unadjust[a-z\s]{0,20}(charg|adjust)|(charg|adjust)[a-z\s]{0,20}unadjust).*", x):
            return("billing_unadjustable charge adjustment_")
    if re.match(r".*((add|get|subscribe|start|subscrip)[a-z\s]{0,20}(vz smart famil|voicemail|hotspot|ringtone|visual voice|verizon cloud|mobile protection|caller id|call filter|google play pass|alexa|disne plus|disne|hulu|verizon roadside assitance|apple music|disney bundle|vz hum|message block|vz navigator|famil locator|espn|apple arcade|verizon home device protect|care smart app|share name id|verizon famil money|verizon visa card|discover|youtube tv|smart locator hub|smart home|icloud|peloton|netflix|plus play|play|ae networks|amc|live nation veep|hulu|ww internation|sling tv|tech coach|call and message block|equipment coverage|mobile secure|paramount|iptv|number lock|verizon mobile protect|total equipment coverage|share number|walmart|hd streaming plus|gaming|xbox|wireless phonepProtect|nfl sunday ticket)|(vz smart famil|voicemail|hotspot|ringtone|visual voice|verizon cloud|mobile protection|caller id|call filter|google play pass|alexa|disne plus|disne|hulu|verizon roadside assitance|apple music|disney bundle|vz hum|message block|vz navigator|famil locator|espn|apple arcade|verizon home device protect|care smart app|share name id|verizon famil money|verizon visa card|discover|youtube tv|smart locator hub|smart home|icloud|peloton|netflix|plus play|play|ae networks|amc|live nation veep|hulu|ww internation|sling tv|tech coach|call and message block|equipment coverage|mobile secure|paramount|iptv|number lock|verizon mobile protect|total equipment coverage|share number|walmart|hd streaming plus|gaming|xbox|wireless phonepProtect|nfl sunday ticket)[a-z\s]{0,20}(add|get|subscribe|start|subscrip)).*", x):
            return("Account_Add Service features")
    if re.match(r".*((remove|disconnect|discontinue|unsubscrib|cancel|delete|drop)[a-z\s]{0,20}(vz smart famil|voicemail|hotspot|ringtone|visual voice|verizon cloud|mobile protection|caller id|call filter|google play pass|alexa|disne plus|disne|hulu|verizon roadside assitance|apple music|disney bundle|vz hum|message block|vz navigator|famil locator|espn|apple arcade|verizon home device protect|care smart app|share name id|verizon famil money|verizon visa card|discover|youtube tv|smart locator hub|smart home|icloud|peloton|netflix|plus play|play|ae networks|amc|live nation veep|hulu|ww internation|sling tv|tech coach|call and message block|equipment coverage|mobile secure|paramount|iptv|number lock|verizon mobile protect|total equipment coverage|share number|walmart|hd streaming plus|gaming|xbox|wireless phonepProtect|nfl sunday ticket)|(vz smart famil|voicemail|hotspot|ringtone|visual voice|verizon cloud|mobile protection|caller id|call filter|google play pass|alexa|disne plus|disne|hulu|verizon roadside assitance|apple music|disney bundle|vz hum|message block|vz navigator|famil locator|espn|apple arcade|verizon home device protect|care smart app|share name id|verizon famil money|verizon visa card|discover|youtube tv|smart locator hub|smart home|icloud|peloton|netflix|plus play|play|ae networks|amc|live nation veep|hulu|ww internation|sling tv|tech coach|call and message block|equipment coverage|mobile secure|paramount|iptv|number lock|verizon mobile protect|total equipment coverage|share number|walmart|hd streaming plus|gaming|xbox|wireless phonepProtect|nfl sunday ticket)[a-z\s]{0,20}(remove|disconnect|discontinue|unsubscrib|cancel|delete|drop)).*", x):
            return("Account_Remove Service features")
    return 'Others'